### ISSUE TITLE
No matching distribution found for tensorflow-text on Windows 10

### ISSUE THREAD

**Issue by antoinecomp** [tensorflow/text#225] opened 2020-02-18 12:37 UTC
When I try to download `tensorflow-text` I have the error message `No matching distribution found for tensorflow-text` and I'm on windows 10. I can't use tensorflow-text yeton Windows, right?

```
(seg_env) C:\Users\antoi\Documents\Programming\Covent Garden\Segmentation>python -m pip install tensorflow-text
ERROR: Could not find a version that satisfies the requirement tensorflow-text (from versions: none)
ERROR: No matching distribution found for tensorflow-text
```

tensorflow 2.1.0
Python 3.6.7

**Comment by broken** [comment] 2020-02-25 18:57
Right. I apologize for this not being available. This is something we really want to provide, but just haven't had the time to work out the problems we ran into it originally.

**Comment by broken** [comment] 2020-02-25 18:58
marking as duplicate of #44

**Closed by broken** 2020-02-25 18:58 UTC
Labels: duplicate
