### ISSUE TITLE
Bert Preprocess Model not working on windows 10

### ISSUE THREAD

**Issue by nassimus26** [tensorflow/text#485] opened 2020-12-31 18:19 UTC
I have the same issue described here [error-with-using-bert-model-from-tensorflow](https://stackoverflow.com/questions/65298391/error-with-using-bert-model-from-tensorflow)

I got this exception when i try the bert preprocessor on windows 10

`Trying to access resource using the wrong type. Expected class tensorflow::lookup::LookupInterface got class tensorflow::lookup::LookupInterface`

**Stack trace**
```
File "C:\work\vpython\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\work\vpython\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\work\vpython\lib\site-packages\tensorflow\python\eager\def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\work\vpython\lib\site-packages\tensorflow\python\eager\function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "C:\work\vpython\lib\site-packages\tensorflow\python\eager\function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\work\vpython\lib\site-packages\tensorflow\python\eager\function.py", line 555, in call
    outputs = execute.execute(
  File "C:\work\vpython\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Trying to access resource using the wrong type. Expected class tensorflow::lookup::LookupInterface got class tensorflow::lookup::LookupInterface
	 [[{{node prediction/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/WordpieceTokenizeWithOffsets/WordpieceTokenizeWithOffsets/WordpieceTokenizeWithOffsets}}]] [Op:__inference_train_function_52076]
Function call stack:
train_function
```

**Comment by nassimus26** [comment] 2020-12-31 18:58
i closed it because i thought it not the right place, but it seams that its related to tensorflow_text

**Comment by broken** [comment] 2021-01-05 20:47
You are correct. The fix should actually be on the TF side, but I've had trouble getting this pushed through because of the holidays. I'm hoping we can resolve this quickly now that everybody is coming back.

ps. This is a duplicate of #476

**Comment by denieboy** [comment] 2021-01-17 18:13
Hi! Any update on this? Or shall we all move to Ubuntu?

**Comment by broken** [comment] 2021-02-03 18:15
Apologies for the delayed response, but this is now fixed in nightly.

**Closed** 2021-02-26 19:13 UTC
