### ISSUE TITLE
pip install tensorflow-text fails on windows

### ISSUE THREAD

**Issue by evyasonov** [tensorflow/text#291] opened 2020-05-27 19:23 UTC
Hey

Seem this issue is actual again: https://github.com/tensorflow/text/issues/89 -- it had a lot of new comments, but it was closed. So I opened this issue.

I've got this error:
```
pip install tensorflow-text
ERROR: Could not find a version that satisfies the requirement tensorflow-text (from versions: none)
ERROR: No matching distribution found for tensorflow-text
```

```
Python:  3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
TF Version:  2.2.0
Eager mode:  True
Hub version:  0.8.0
GPU is NOT AVAILABLE
Windows 10
```

Can you help please

Thanks in advance

**Comment by sidambhire** [comment] 2020-06-01 02:28
It is also not working on Arch Linux. 
```
Linux 5.4.43-1-MANJARO
Python 3.8.3
```
I have tensorflow-gpu installed.

**Comment by sidambhire** [comment] 2020-06-01 04:05
I managed to install this package using python 3.6. I think this bug is related to #284.

**Comment by evyasonov** [comment] 2020-06-01 08:03
Tried python 3.6 -- still don't work for me:

```
(tf) C:\Users\Ev>python --version
Python 3.6.10 :: Anaconda, Inc.

(tf) C:\Users\Ev>pip install tensorflow-text
ERROR: Could not find a version that satisfies the requirement tensorflow-text (from versions: none)
ERROR: No matching distribution found for tensorflow-text
```

**Comment by broken** [comment] 2020-06-05 18:00
Yeah; this is a duplicate of #44. We do not have windows targets at this time. We've been busy getting components ready for the TF 2.3 release, but adding support for Windows is something we very much want to squeeze in too.

**Comment by evyasonov** [comment] 2020-06-27 22:57
Thanks for the answer. Will wait for windows version

**Comment by broken** [comment] 2020-07-15 23:35
We were trying to get this into 2.3.x, but missed the deadline. I expect a Windows release with 2.4.

**Closed by broken** 2020-07-15 23:35 UTC

**Comment by azmainamin** [comment] 2020-10-11 00:22
@broken Any ETA on 2.4 and this fix?

**Comment by MartinoMensio** [comment] 2021-03-07 10:11
I see that the latest release 2.4.3 has Windows wheels https://pypi.org/project/tensorflow-text/2.4.3/#files but I don't have any Windows machine to test it on. Can anyone confirm that it is working?

**Comment by JordanSimba** [comment] 2021-07-12 13:04
@MartinoMensio `pip install tensorflow-text` worked just fine on my windows machine

**Comment by broken** [comment] 2021-07-12 18:16
I'm happy it's working for you.

FYI, nobody on the team monitors closed issues, so we missed all of these replies. Please create a new issue if the original fix for a problem does not work for you. Thanks!
