### ISSUE TITLE
install through pip with tensorflow gpu

### ISSUE THREAD

**Issue by anirudhraju** [tensorflow/text#268] opened 2020-04-14 07:32 UTC
What's the best way to pip install tensorflow_text with an existing tensorflow gpu wheel already installed?

I'm running the below command, but it seems to be looking for tensorflow CPU installation only.  
`pip install tensorflow_text-2.0.0-cp36-cp36m-manylinux1_x86_64.whl  -f wheels/ --no-index -v `
The wheels/ dir above has all of the tensorflow-gpu related wheels and obtained through pip download tensorflow-gpu

Note that directly installing tensorflow_text seems to install the CPU version of tensorflow

Error message:
```
  Skipping link file://wheels/numpy-1.17.2-cp36-cp36m-manylinux1_x86_64.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/decorator-4.4.2-py2.py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/tensorflow_gpu-2.0.0-cp36-cp36m-manylinux2010_x86_64.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/opt_einsum-3.1.0.tar.gz; Missing project version for tensorflow
  Skipping link file://wheels/setuptools-41.4.0-py2.py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/astor-0.8.0-py2.py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/Markdown-3.1.1-py2.py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/absl-py-0.8.0.tar.gz; Missing project version for tensorflow
  Skipping link file://wheels/cloudpickle-1.1.1-py2.py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/gast-0.2.2.tar.gz; Missing project version for tensorflow
  Skipping link file://wheels/six-1.12.0-py2.py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/wrapt-1.11.2.tar.gz; Missing project version for tensorflow
  Skipping link file://wheels/tensorflow_probability-0.8.0-py2.py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/tensorflow_addons-0.6.0-cp36-cp36m-manylinux2010_x86_64.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/protobuf-3.10.0-cp36-cp36m-manylinux1_x86_64.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/Werkzeug-0.16.0-py2.py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/tensorboard-2.0.0-py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/wheel-0.33.6-py2.py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/pip-19.0.1-py2.py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/Keras_Applications-1.0.8-py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/google_pasta-0.1.7-py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/tensorflow_text-2.0.0-cp36-cp36m-manylinux1_x86_64.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/termcolor-1.1.0.tar.gz; Missing project version for tensorflow
  Skipping link file://wheels/tensorflow_estimator-2.0.0-py2.py3-none-any.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/grpcio-1.24.1-cp36-cp36m-manylinux1_x86_64.whl; wrong project name (not tensorflow)
  Skipping link file://wheels/h5py-2.10.0-cp36-cp36m-manylinux1_x86_64.whl; wrong project name (not tensorflow)
  Could not find a version that satisfies the requirement tensorflow<2.1,>=2.0.0 (from tensorflow-text==2.0.0) (from versions: )
Cleaning up...
Removed build tracker '/storage/tmp/pip-req-tracker-4zv0mcxe'
No matching distribution found for tensorflow<2.1,>=2.0.0 (from tensorflow-text==2.0.0)
```

**Comment by broken** [comment] 2020-06-06 00:55
The current workaround is to install TF Text, then reinstall tensorflow-gpu.

This is a known problem and please visit https://github.com/tensorflow/text/issues/195 to understand why this is the case. We haven't had any time to experiment with this, but are open to suggestions on how we can address it.

**Comment by broken** [comment] 2020-06-06 00:57
I'm closing due to it being a duplicate of #195. Please add comments to that issue if you have any more questions or suggestions.

**Closed by broken** 2020-06-06 00:57 UTC
Labels: duplicate
