### ISSUE TITLE
[Installation Issue]Getting error while istalling tensorflow-text

### ISSUE THREAD

**Issue by Alisha1992** [tensorflow/text#430] opened 2020-11-10 10:06 UTC
I am trying to install `tensorflow-text` but getting the following error when I do 'pip install tensorflow-text==2.2.1'

ERROR: Could not find a version that satisfies the requirement tensorflow-text==2.2.1 (from versions: none)
ERROR: No matching distribution found for tensorflow-text==2.2.1

I have windows 10, python 3.7, x64.

From what I understand, currently, tensorflow-text isn't available for Windows, so could you guys provide any resolution for this?

**Comment by broken** [comment] 2020-11-18 21:53
2.4.0 should be the first version to support windows. We just released a release candidate (2.4.0-rc0), so I encourage you to try it and let us know if there are issues.

**Comment by broken** [comment] 2020-11-18 21:54
closing as duplicate of #44

**Closed by broken** 2020-11-18 21:53 UTC
