### ISSUE TITLE
Cannot serve model with v2.1.1 and TF Serving 2.2.0-rc1

### ISSUE THREAD

**Issue by elmadj** [tensorflow/text#281] opened 2020-04-27 13:52 UTC
Hi there !

We're using TF Serving 2.2.0-rc1 to serve a model  which uses the BERT tokenizer (tensorflow/text version v2.1.1). TF Serving starts and shows no error about missing ops. But then, when we try to call the API, it returns: 
`{'error': 'U_FILE_ACCESS_ERROR: Could not retrieve ICU NFKC_CaseFold normalizer\n\t [[{{node CaseFoldUTF8/CaseFoldUTF8}}]]'}` .

Anything we are missing when building our docker image ?

Here are the logs :

`2020-04-27 13:41:46.870282: I tensorflow_serving/model_servers/server_core.cc:464] Adding/updating models.
2020-04-27 13:41:46.870316: I tensorflow_serving/model_servers/server_core.cc:575]  (Re-)adding model: mymodel
2020-04-27 13:41:46.971922: I tensorflow_serving/core/basic_manager.cc:739] Successfully reserved resources to load servable {name: mymodel version: 1}
2020-04-27 13:41:46.972053: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: mymodel version: 1}
2020-04-27 13:41:46.972109: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: mymodel version: 1}
2020-04-27 13:41:46.972258: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /models/mymodel/1
2020-04-27 13:41:47.026067: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
2020-04-27 13:41:47.026114: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:264] Reading SavedModel debug info (if present) from: /models/mymodel/1
2020-04-27 13:41:47.026236: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-27 13:41:47.108802: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:203] Restoring SavedModel bundle.
2020-04-27 13:41:47.251983: W external/org_tensorflow/tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 89075712 exceeds 10% of free system memory.
2020-04-27 13:41:47.558168: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:152] Running initialization op on SavedModel bundle at path: /models/mymodel/1
2020-04-27 13:41:47.629049: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:333] SavedModel load for tags { serve }; Status: success: OK. Took 656807 microseconds.
2020-04-27 13:41:47.638016: I tensorflow_serving/servables/tensorflow/saved_model_warmup.cc:105] No warmup data file found at /models/mymodel/1/assets.extra/tf_serving_warmup_requests
2020-04-27 13:41:47.638652: I tensorflow_serving/core/loader_harness.cc:87] Successfully loaded servable version {name: mymodel version: 1}
2020-04-27 13:41:47.640812: I tensorflow_serving/model_servers/server.cc:355] Running gRPC ModelServer at 0.0.0.0:8500 ...
[warn] getaddrinfo: address family for nodename not supported
2020-04-27 13:41:47.642975: I tensorflow_serving/model_servers/server.cc:375] Exporting HTTP/REST API at:localhost:8501 ...
[evhttp_server.cc : 238] NET_LOG: Entering the event loop ...`

**Comment by tgsmith61591** [comment] 2020-04-27 16:06
I can confirm I'm getting the same error with `tensorflow==2.2.0rc3`

**Comment by tgsmith61591** [comment] 2020-04-28 17:04
@broken I have a PR to fix this in the serving side: https://github.com/tensorflow/serving/pull/1616
Really curious for your thoughts. It appears to be an issue with the way they were patching `icu`. Not sure if you're involved on the serving side, but would be good for you to look at in any case.

**Comment by gregbillock** [comment] 2020-05-12 20:32
Thanks, I just made a new release of tf.text for 2.2.0 and haven't done the tf serving step yet. Hopefully this gets solved this week. Also pinged internally on the PR to see if we can get attention on it.

**Comment by broken** [comment] 2020-05-14 07:05
To keep this thread updated as well, my initial guess is that this is due to an update to Bazel on TF Serving side which should be fixed with a simple update to their workspace files. I think it's best to move most discussion there and to Taylor's PR, and we can just update here with the conclusion.

**Comment by broken** [comment] 2020-05-29 00:58
The fix for this bug as well as the test that didn't catch it should be checked in now. I expect the next version of nightly for TF model server should contain the changes as well as their 2.2.0 release.

**Comment by broken** [comment] 2020-06-02 22:38
Just confirmed the change has been cherry-picked into the release.

**Closed by broken** 2020-06-02 22:38 UTC

**Comment by elmadj** [comment] 2020-06-08 12:29
I can confirm this is working now. Thank you !
