### ISSUE TITLE
Can not build on Apple Silicon from source.

### ISSUE THREAD

**Issue by sun1638650145** [tensorflow/text#538] opened 2021-03-02 05:04 UTC
I have a Apple M1 Mac. And TensorFlow can run on it([tensorflow_macos](https://github.com/apple/tensorflow_macos)). TF Text has no pre-compiled packages in PyPI, so I need to build it myself.  I known that TF Text needs to be built in TensorFlow environment, but package name is tensorflow_macos in Apple M1 Mac. What should I do?

**Comment by broken** [comment] 2021-04-08 19:22
I apologize for the delayed response, but I'll see if I can get my hands on a M1 Mac and reply back soon.

**Comment by broken** [comment] 2021-04-23 17:43
The repo you linked to is actually owned and operated by Apple. They created it after the launch of the M1 chip. If you would like TF Text to be included, your best bet would be to create an issue for them.

Unfortunately, we cannot support M1 related issues at this time. If the team at Apple is unwilling, but you want to take it on yourself, I will be happy to review any changes for manually building a package.

**Comment by sun1638650145** [comment] 2021-04-24 05:54
Thanks for your reply. I will create a new issue under tensorflow-macos.

**Comment by hudozhnin** [comment] 2021-06-08 14:42
@sun1638650145 they archived discussion at macos repo, did you manage to get some progress in this question? 
Is it possible to somehow run tf_text on m1? :(

**Comment by sun1638650145** [comment] 2021-06-09 03:27
@hudozhnin Now, TensorFlow v2.5 has native support for Apple Silicon. So I tried to compile from source again. Unfortunately I still couldn't solve it because of the tool chains.

**Comment by dawsoneliasen** [comment] 2021-06-14 21:48
@broken Does the change to the way TF is supported on Mac change your status on this?

I've been playing around with the build to try to get it to work, but haven't been able to figure it out.  Is the problem still something that needs to be changed in the TF build, or is it something that can be fixed in the build files here? If the latter, could you point me in the right direction?

**Comment by broken** [comment] 2021-06-15 19:36
Yes; that does change our position. I do know offhand what needs to be changed as the work has been pushed back (we didn't expect this to get into 2.5), but I will work with TF infra and see what is required.

**Comment by broken** [comment] 2021-06-15 20:50
FYI; #638 has somebody that successfully built this from source. You may want to take a look at his steps while our team investigates adding this package.

**Comment by dawsoneliasen** [comment] 2021-06-15 20:53
broken, thanks so much. I did see that in #638 -- I will try that in the meantime. Cheers!

**Comment by sun1638650145** [comment] 2021-06-16 00:22
@dawsoneliasen Hi, I found that #638 was built on Intels Mac, if your M1 builds successfully please let me know, thanks.

**Comment by broken** [comment] 2021-06-22 18:21
@dawsoneliasen @sun1638650145 I talked to the team responsible for TF's builds to get ours aligned and they said there hasn't been any change in support for M1 Macs. What this means unfortunately is that we will not be changing our position at this time.

It sounds like the toolchain is the current problem. Can you look at Apple's repo and see how they handled this for TF? Maybe you can simply swap them out.

Another idea is to check out the two repositories (tensorflow & tensorflow_macos) at the same relative commit and diff the directories to see what build items need to be changed.

**Comment by sun1638650145** [comment] 2021-06-22 23:33
@broken Unfortunately, tf-macos is not open source.

**Comment by broken** [comment] 2021-06-24 19:06
Ugh; you're right. The problem is our builds leverage much of core TF's build infrastructure. If you look in our configure.sh, you'll see that the toolchain is taken directly from TF; so until they make the necessary changes, we will not be able to support M1s.

**Closed** 2021-12-03 04:53 UTC
Labels: enhancement
