### ISSUE TITLE
`Op type not registered RegexSplitWithOffsets` when running TF Text v1.15.1 in TF Transform component via Kubeflow

### ISSUE THREAD

**Issue by jshph** [tensorflow/text#261] opened 2020-04-02 17:20 UTC
I have installed TF Text v1.15.1 on Kubeflow (and Dataflow workers) and am running `BertTokenizer.tokenize` in a TF Transform component. I get the error `Op type not registered 'RegexSplitWithOffsets'`; here is a partial stack trace from Kubeflow logs:
```
  File "apache_beam/runners/common.py", line 895, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "/usr/local/lib/python3.6/site-packages/tensorflow_transform/beam/impl.py", line 462, in process
    lambda: self._make_graph_state(saved_model_dir))
  File "/usr/local/lib/python3.6/site-packages/tfx_bsl/beam/shared.py", line 221, in acquire
    return _shared_map.acquire(self._key, constructor_fn)
  File "/usr/local/lib/python3.6/site-packages/tfx_bsl/beam/shared.py", line 184, in acquire
    result = control_block.acquire(constructor_fn)
  File "/usr/local/lib/python3.6/site-packages/tfx_bsl/beam/shared.py", line 87, in acquire
    result = constructor_fn()
  File "/usr/local/lib/python3.6/site-packages/tensorflow_transform/beam/impl.py", line 462, in <lambda>
    lambda: self._make_graph_state(saved_model_dir))
  File "/usr/local/lib/python3.6/site-packages/tensorflow_transform/beam/impl.py", line 438, in _make_graph_state
    self._exclude_outputs, self._tf_config)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_transform/beam/impl.py", line 341, in __init__
    saved_model_dir, {}))
  File "/usr/local/lib/python3.6/site-packages/tensorflow_transform/saved/saved_transform_io.py", line 397, in partially_apply_saved_transform_internal
    saved_model_dir, logical_input_map, tensor_replacement_map)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_transform/saved/saved_transform_io.py", line 240, in _partially_apply_saved_transform_impl
    input_map=input_map)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1453, in import_meta_graph
    **kwargs)[0]
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1477, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/meta_graph.py", line 809, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
RuntimeError: tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'RegexSplitWithOffsets' in binary
```
I am running this on Tensorflow 1.15.2 and TF Transform 0.15.0.

When I run the transform using a local Beam graph, it runs without issue and writes out TF records to disk. I install tensorflow-text on the Dataflow workers by supplying an `--extra_package` arg. I'm getting no error issues in worker startup logs that the package failed to install. But I am curious if all was done that's necessary to setup tensorflow-text on these workers.

Reverting to v1.15.0rc0 also reverts the `regex_split_ops` in question, but even after fixing the issue with `merge_dims` I get an issue with `UnicodeScriptTokenizeWithOffsets` op type not registered.

I'm eager to get TF Text running in our production Kubeflow pipeline, but I'm a little out of ideas and would appreciate insights!!

I have filed an issue in TF Transform here: https://github.com/tensorflow/transform/issues/170
Tagging @andrewsmartin who has helped me debug internally.

**Comment by broken** [comment] 2020-06-06 01:20
Joshua, I'm sorry this issue has taken so long to get a response to. I'm unfamiliar with Kubeflow, but the "Op type not registered" usually means that they binary that is trying to run the ops did not build in the tf text ops. I expect that the --extra_package arg is just for the python packages, but this does not actually build in the backing c++ kernel op code.

**Comment by broken** [comment] 2020-07-15 23:40
TF.Transform has addressed this on their end (tensorflow/transform@7ec6244). This should be fixed in their next release.

I'm going to close this as a duplicate of #311.

**Closed** 2020-07-15 23:41 UTC
Labels: duplicate, help wanted
