### ISSUE TITLE
import tensorflow_text gives errors in 2.3.0 on mac

### ISSUE THREAD

**Issue by mchari** [tensorflow/text#402] opened 2020-09-22 17:37 UTC
I did a 
pip install tensorflow
pip install tensorflow_text

to get 2.3.0 versions.  I am using python 3.7.

When I tried to import tensorflow_text , I get the following traceback

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.7/site-packages/tensorflow_text/__init__.py", line 22, in <module>
    from tensorflow_text.python.ops import *
  File "/anaconda3/lib/python3.7/site-packages/tensorflow_text/python/ops/__init__.py", line 23, in <module>
    from tensorflow_text.python.ops.bert_tokenizer import BertTokenizer
  File "/anaconda3/lib/python3.7/site-packages/tensorflow_text/python/ops/bert_tokenizer.py", line 30, in <module>
    from tensorflow_text.python.ops.normalize_ops import case_fold_utf8
  File "/anaconda3/lib/python3.7/site-packages/tensorflow_text/python/ops/normalize_ops.py", line 28, in <module>
    gen_normalize_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_normalize_ops.dylib'))
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/anaconda3/lib/python3.7/site-packages/tensorflow_text/python/ops/_normalize_ops.dylib, 6): Symbol not found: ____chkstk_darwin
  Referenced from: /anaconda3/lib/python3.7/site-packages/tensorflow_text/python/ops/_normalize_ops.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /anaconda3/lib/python3.7/site-packages/tensorflow_text/python/ops/_normalize_ops.dylib

**Comment by broken** [comment] 2020-09-22 19:32
This is actually a duplicate of #375. I thought this was fixed, but I see it's still opened. I'll look into where this was left.

**Comment by broken** [comment] 2020-09-22 19:33
Further updates I'll post to that original issue.

**Closed** 2020-09-22 19:32 UTC
Labels: duplicate
