### ISSUE TITLE
Error while importing Tensorflow-text: undefined symbol

### ISSUE THREAD

**Issue by Tangogow** [tensorflow/text#963] opened 2022-06-30 17:51 UTC
Tensorflow-text: **2.9.0**
Tensorflow: 2.9.1
Python: 3.7.13

Happen only with **2.9.0**
2.10.0b2 and 2.8.2rc1 seems to be working.

In Google Collab.

Similar to closed #325 two years ago.

```python
import tensorflow_text as text
```
```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-30-40513338c6fc>](https://localhost:8080/#) in <module>()
      1 import tensorflow_hub as hub
      2 import pandas as pd
----> 3 import tensorflow_text as text
      4 import matplotlib.pyplot as plt
      5 from sklearn.model_selection import train_test_split

[/usr/local/lib/python3.7/dist-packages/tensorflow_text/__init__.py](https://localhost:8080/#) in <module>()
     18 

     19 # pylint: disable=wildcard-import
---> 20 from tensorflow_text.core.pybinds import tflite_registrar
     21 from tensorflow_text.python import keras
     22 from tensorflow_text.python import metrics

ImportError: /usr/local/lib/python3.7/dist-packages/tensorflow_text/core/pybinds/tflite_registrar.so: undefined symbol: _ZN4absl12lts_2021110220raw_logging_internal21internal_log_functionB5cxx11E
```

**Comment by broken** [comment] 2022-07-07 00:52
Do you have an example colab? When I try this using one of the guides (and editing it to use `tensorflow_text==2.9.*`) I don't have the same issue.
https://colab.research.google.com/github/tensorflow/text/blob/master/docs/guide/tokenizers.ipynb#scrollTo=ISEUjIsYAl2S

What I think may be happening is that you are importing tensorflow before pip installing tensorflow_text. That loads TF libs in colab that are incompatible with tf text 2.9.x. The default TF of Colab is 2.8.2 at the moment, which would explain why TF Text 2.8.x (and 2.10 beta) work because they are built to work with TF 2.8.x, so Colab does not need to pip install a new version of TF.

If you disconnect the runtime, connect again, and pip install tensorflow_text with the first code block, do you receive the same error?

**Comment by sungengyi** [comment] 2022-07-12 21:27
[https://colab.research.google.com/drive/1z5Z_pTMydh778t51BXY9S_AroaVz1GjY?usp=sharing](url)

: ) Here you go. 
tensorflow_text is always the first thing I pip installed, and I checked tf.__version__ is indeed 2.9.1.

**Comment by jessechancy** [comment] 2022-07-12 22:20
Have the same problem too! Only stopped working today

**Comment by sungengyi** [comment] 2022-07-12 22:29
> Have the same problem too! Only stopped working today

I've encountered several sudden version issues on colab with tf/keras in the past 2 month... 

I was using codes from the older tutorial then after May 23rd the code broke. I rewrote it with the up-to-date version but cannot get the model to perform the same anymore...

**Comment by broken** [comment] 2022-07-13 00:12
My example looks like it is failing now too. There doesn't seem to be a problem outside of colab. Let me find somebody that can help out with this.

**Comment by broken** [comment] 2022-07-13 00:31
Trying to install 2.8.x versions results in an error from tfm too.

```
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-3b7de3fd28ed>](https://localhost:8080/#) in <module>()
----> 1 import tensorflow_models as tfm

19 frames
[/usr/local/lib/python3.7/dist-packages/cv2/gapi/__init__.py](https://localhost:8080/#) in <module>()
    288 
    289 
--> 290 cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline

AttributeError: module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline'
```

**Comment by broken** [comment] 2022-07-13 01:33
Colab is now aware of the issue and is looking into it.

**Comment by sungengyi** [comment] 2022-07-13 22:20
@broken Yes, I can confirm tfm can be imported and run before Monday Jun11th. I think it broke roughly the same time as tf text. 

`AttributeError: module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline'`

This is the new error I got. I guess colab has its environment updated on May 23rd and Jun11th. Then the versions don't match anymore and cause my first issue and this one.

**Comment by broken** [comment] 2022-07-20 20:54
The problem with tensorflow_models is now fixed in colab too.

@sungengyi I confirmed with your example above.

cheers!

**Closed** 2022-07-27 00:25 UTC

**Comment by steve-marmalade** [comment] 2022-08-15 19:17
I just encountered this issue after running `pip install tensorflow-text==2.9.0` in a container image based on the m95 deeplearning release of [tf-gpu.2-9](https://console.cloud.google.com/artifacts/docker/deeplearning-platform-release/us/gcr.io/tf-gpu.2-9/sha256:5673e098626d345377220e4e90dfae7f85956ba25f21c40e1d14c01db6a749af), which [was announced on 8/12/22.](https://cloud.google.com/deep-learning-containers/docs/release-notes#August_12_2022)

```
>>> import tensorflow_text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_text/__init__.py", line 20, in <module>
    from tensorflow_text.core.pybinds import tflite_registrar
ImportError: /opt/conda/lib/python3.7/site-packages/tensorflow_text/core/pybinds/tflite_registrar.so: undefined symbol: _ZN4absl12lts_2021110220raw_logging_internal21internal_log_functionB5cxx11E
```

Is the solution that was identified for colab something I can manually run?

**Comment by broken** [comment] 2022-08-19 21:58
I think this may be because you are using conda. Can you try it with the system install or pyenv?  See #644 for more info on this.

**Comment by andysingal** [comment] 2023-06-11 15:47
I am having issue:
import tensorflow_models as tfm
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-2-1683ec09a249>](https://localhost:8080/#) in <cell line: 6>()
      4 import numpy as np
      5 import tensorflow as tf
----> 6 import tensorflow_models as tfm
      7 
      8 import time

21 frames
[/usr/local/lib/python3.10/dist-packages/keras/utils/__init__.py](https://localhost:8080/#) in <module>
     18 
     19 # Serialization related
---> 20 from keras.saving.legacy.serialization import deserialize_keras_object
     21 from keras.saving.legacy.serialization import serialize_keras_object
     22 from keras.saving.object_registration import CustomObjectScope

ImportError: cannot import name 'deserialize_keras_object' from partially initialized module 'keras.saving.legacy.serialization' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/keras/saving/legacy/serialization.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by moisesosorio** [comment] 2023-09-23 11:44
I got the same error, somebody found the solution?

cannot import name 'deserialize_keras_object' from partially initialized module 'keras.saving.legacy.serialization' (most likely due to a circular import) (/home/mosorio/Developments/dsProject/jupyter/venv/lib/python3.10/site-packages/keras/saving/legacy/serialization.py)

**Comment by broken** [comment] 2023-09-25 19:03
@moisesosorio This looks like a Keras issue. You should open an issue in with Keras and ask them.
